@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC90b2tlbiIsImlhdCI6MTY1NDczODM5NSwiZXhwIjoxNjU0NzM4NTQ0LCJuYmYiOjE2NTQ3Mzg0ODQsImp0aSI6IjhBalVHTkdBWHRxOUZteFkiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.fww4ibujzT1peaUlKG0c7RyCRflruRMvp3Z8ayf7DEs
### LOGIN
POST http://localhost:8000/api/auth/login
content-type: application/json

{
   "email":"duytrung341@gmail.com",
   "password":"12345"
}

### REGISTER
POST http://localhost:8000/api/auth/registry
content-type: application/json

{
   "fullname":"Duy Trung",
   "email":"duytrung341@gmail.com",
   "password":"12345"
}

### VERIFY
POST http://localhost:8000/api/auth/verify/5
content-type: application/json

{
   "code":580227
}

### ME
POST http://localhost:8000/api/auth/me
Authorization: {{token}}

### LOGOUT
POST http://localhost:8000/api/auth/logout
Authorization: {{token}}


### token
POST http://localhost:8000/api/auth/token
Authorization:{{token}}