@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MjMxNzQ3MCwiZXhwIjoxNjUyNDI1NDcwLCJuYmYiOjE2NTIzMTc0NzEsImp0aSI6InhzSDJEMXMzWmo0OUgzaDEiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Bn0wspfOtKdVEccST-IRbfMFcd6DWOQbajX93QSsryc

### get cart
POST http://localhost:8000/api/cart/get
content-type: application/json
Authorization: {{token}}

### add cart
POST http://localhost:8000/api/cart/add_cart
content-type: application/json
Authorization: {{token}}

{
   "productId":"5",
   "quantity":1
}

### update cart
POST http://localhost:8000/api/cart/update
content-type: application/json
Authorization: {{token}}

{
   "productId":"5",
   "quantity":2
}

### remove cart item
POST http://localhost:8000/api/cart/remove
content-type: application/json
Authorization: {{token}}

{
   "productId":"5"
}

### clear cart
POST http://localhost:8000/api/cart/clear
content-type: application/json
Authorization: {{token}}


### clear cart
POST http://localhost:8000/api/order/history
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MjQ0MzA4OSwiZXhwIjoxNjUyNTUxMDg5LCJuYmYiOjE2NTI0NDMwODksImp0aSI6Im5aR2dLYkU1N3FNMk50aW0iLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.el68RXVXQ8Z6AMBRlUywvflHUbiAsvo0pwXGhHqH_-8

