@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9yZWdpc3RlciIsImlhdCI6MTY1NDE1NTA1OCwiZXhwIjoxNjU0MjYzMDU4LCJuYmYiOjE2NTQxNTUwNTgsImp0aSI6Ik1FRnlSV2pEZ2VvZFFkUTIiLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.OxYTHB7R2-NQZm-ygJsEAydRM-UbOtbV1A7cfQApL1I

### get cart
POST http://localhost:8000/api/cart/get
content-type: application/json
Authorization: {{token}}

### add cart
POST http://localhost:8000/api/cart/add_cart
content-type: application/json
Authorization: {{token}}

{
   "productId":"5",
   "quantity":1
}

### update cart
POST http://localhost:8000/api/cart/update
content-type: application/json
Authorization: {{token}}

{
   "productId":"5",
   "quantity":2
}

### remove cart item
POST http://localhost:8000/api/cart/remove
content-type: application/json
Authorization: {{token}}

{
   "productId":"5"
}

### clear cart
POST http://localhost:8000/api/cart/clear
content-type: application/json
Authorization: {{token}}


### clear cart
POST http://localhost:8000/api/order/history
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MjQ0MzA4OSwiZXhwIjoxNjUyNTUxMDg5LCJuYmYiOjE2NTI0NDMwODksImp0aSI6Im5aR2dLYkU1N3FNMk50aW0iLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.el68RXVXQ8Z6AMBRlUywvflHUbiAsvo0pwXGhHqH_-8

