@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MjY2MTExNiwiZXhwIjoxNjUyNzY5MTE2LCJuYmYiOjE2NTI2NjExMTYsImp0aSI6IktVek02WUpDTTBSZ01vMTciLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.lt6nwOtUPhROhZ5w8-QqRtB2-emyEYjO-BDsi_yxuwM

### get cart
POST http://localhost:8000/api/products?minPrice=10000&maxPrice=25000
content-type: application/json
Authorization: {{token}}

{
   "pathname":"/categories/fantasy"
}

### get cart
POST http://localhost:8000/api/product_reviews
content-type: application/json

{
   "productId":14
}