<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('id' => '1', 'name' => 'The White House', 'brand_id' => '1', 'price' => '25000', 'sale_price' => '25000', 'quantity' => '5', 'description' => '<p>You’re busy. It feels like you’re always on the go. So when you do get some free time, you like to recharge your batteries by focusing on a fun, creative challenge. That’s what building The White House with LEGO® bricks is all about.</p>

<p>Revel in the details<br/>
With this hands-on, minds-on craft project, you\'ll recreate details from the neoclassical columns of the president\'s Executive Residence and colonnades connecting the East and West Wings to the surrounding gardens and fountain. This LEGO Architecture White House model (21054) can be divided into 3 sections for closer inspection and includes a LEGO brick inscribed ‘The White House’ to complete an inspiring display piece.</p>

<p>LEGO sets for your lifestyle<br/>
Escape the daily grind and click your stress away creating this stylish model that will look great in your home or office. Part of a collection of LEGO building sets for adults interested in art, design, architecture and pop culture, it makes the best gift for you or the hobbyist inyour life.</p>
<p>You’re busy. It feels like you’re always on the go. So when you do get some free time, you like to recharge your batteries by focusing on a fun, creative challenge. That’s what building The White House with LEGO® bricks is all about.</p>

<p>Revel in the details<br/>
With this hands-on, minds-on craft project, you\'ll recreate details from the neoclassical columns of the president\'s Executive Residence and colonnades connecting the East and West Wings to the surrounding gardens and fountain. This LEGO Architecture White House model (21054) can be divided into 3 sections for closer inspection and includes a LEGO brick inscribed ‘The White House’ to complete an inspiring display piece.</p>

<p>LEGO sets for your lifestyle<br/>
Escape the daily grind and click your stress away creating this stylish model that will look great in your home or office. Part of a collection of LEGO building sets for adults interested in art, design, architecture and pop culture, it makes the best gift for you or the hobbyist inyour life.</p><ul><li>This LEGO® Architecture display model of The White House (21054) beautifully captures the neoclassical design and splendor of this world-famous residence occupied by every United States president since 1800.</li><li>Enjoy this LEGO® building set for adults, featuring details like the Executive Residence, West Wing, East Wing and connecting colonnades of The White House, plus the Rose Garden and Jacqueline Kennedy Garden.</li><li>The model can easily be divided into 3 sections for closer inspection of the architectural details. It also has a LEGO® brick inscribed ‘The White House’ to complete a conversation-starting display piece.</li><li>If you’ve been to or dream of visiting The White House, 1600 Pennsylvania Avenue, Washington DC, or you just love travel, architecture, history and design, this is the creative building kit for you.</li><li>Measuring 4” (11cm) high, 18” (47cm) wide and 7” (20cm) deep, this buildable LEGO® Architecture model is a super display item for your home or office. It\'s also makes the best gift for creative friends.</li><li>No batteries required – this stylish DIY project is all about recreating The White House with LEGO® bricks and immersing yourself in a focused activity that leaves you feeling relaxed and refreshed when you’re finished.</li><li>Includes clear instructions so even LEGO® newcomers can build with confidence, plus a coffee-table-style booklet telling The White House story (English language only. Download other languages at LEGO.com/architecture).</li><li>This construction set for adults is part of a collection of inspiring LEGO® model kits designed for you, the discerning hobbyist, as you look for your next creative project.</li><li>LEGO® building bricks meet the highest industry standards, which ensures they are consistent, compatible and connect and pull apart easily every time – it\'s been that way since 1958.</li><li>LEGO® bricks and pieces are rigorously tested, ensuring that every construction set meets the highest safety and quality standards, which means this White House miniature model is as robust as it is beautiful.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/dcff4c74e0275aa47cb378080605a92f.png', 'slug' => 'the-white-house', 'created_at' => '2022-05-19 01:06:41', 'updated_at' => '2022-05-19 01:06:41'),
            array('id' => '2', 'name' => 'Statue of Liberty', 'brand_id' => '1', 'price' => '30000', 'sale_price' => '25000', 'quantity' => '5', 'description' => '<p>Celebrate a monumental blend of architecture and sculpture with this LEGO® Architecture 21042 The Statue of Liberty set. America’s iconic symbol of freedom stands more than 305 feet above Liberty Island in New York harbor, welcoming seafarers from around the globe. This impressive LEGO interpretation faithfully reproduces the monument\'s harmonious blend of sculpture and architecture with its intricately detailed shield-lined pedestal, brick detailing and columned balconies. The beautifully crafted Lady Liberty statue features a flowing robe, broken shackles, 7-ray crown, iconic tablet and an upraised arm bearing a golden torch. Finished with an authentic sand-green and beige color scheme, and a decorative nameplate, this model delivers a highly satisfying building experience to all with an interest in architecture, travel, history and design, and makes a truly symbolic centerpiece for the home or office.                                                                                   </p>
<p>Celebrate a monumental blend of architecture and sculpture with this LEGO® Architecture 21042 The Statue of Liberty set. America’s iconic symbol of freedom stands more than 305 feet above Liberty Island in New York harbor, welcoming seafarers from around the globe. This impressive LEGO interpretation faithfully reproduces the monument\'s harmonious blend of sculpture and architecture with its intricately detailed shield-lined pedestal, brick detailing and columned balconies. The beautifully crafted Lady Liberty statue features a flowing robe, broken shackles, 7-ray crown, iconic tablet and an upraised arm bearing a golden torch. Finished with an authentic sand-green and beige color scheme, and a decorative nameplate, this model delivers a highly satisfying building experience to all with an interest in architecture, travel, history and design, and makes a truly symbolic centerpiece for the home or office.                                                                                   </p><ul><li> LEGO® Architecture interpretation of the real-world architectural landmark, the Statue of Liberty.
</li><li> Features an intricately detailed pedestal with shield & brick detailing, columned balconies, and a Lady Liberty statue with a flowing robe, 7-ray crown, iconic tablet and golden torch.
</li><li> The included booklet contains information about the design, architecture and history of the building (English and French languages only. Other languages available for download at LEGO.com/architecture).
</li><li> LEGO® Architecture celebrates the world of architecture through the medium of the LEGO brick, and is developed for all with an interest in travel, architecture, history and design.
</li><li> This set includes over 1,685 LEGO® pieces.
</li><li> Enjoy a pleasantly challenging and rewarding building experience with this LEGO® Architecture set.
</li><li> Measures over 17” (44cm) high, 5” (14cm) wide and 5” (14cm) deep.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/9ff3547c80a9f902d3a91f3e62060cae.png', 'slug' => 'statue-of-liberty', 'created_at' => '2022-05-19 01:06:42', 'updated_at' => '2022-05-19 01:06:42'),
            array('id' => '3', 'name' => 'Taj Mahal', 'brand_id' => '1', 'price' => '27000', 'sale_price' => '27000', 'quantity' => '5', 'description' => '<p>Whether you have been lucky enough to visit the Taj Mahal yourself and want a special souvenir of the experience, dream of visiting one day or just appreciate elegant buildings, this LEGO® Architecture Landmarks Collection set (21056) is ideal for you.</p>

<p>Wondrous details<br/>
This inspiring, hands-on challenge to enjoy in your spare time lets you recreate a symbol of eternal love and an architectural wonder of the world in LEGO style. Revel in authentic details such as the crypt with tombs of Mumtaz and Shah Jahan, central chamber with 2 cenotaphs, monumental iwans, main dome, 4 chhatris and 4 slender minarets. A LEGO brick inscribed ‘Taj Mahal’ completes a scale model that is sure to wow people wherever it is displayed.</p>

<p>Delightful gift<br/>
Part of a collection of premium-quality LEGO model kits for adults, this set makes a fantastic treat for yourself. It also makes an inspirational gift for LEGO fans and anyone in your life who is passionate about the Taj Mahal, India, travel or architecture.</p>
<p>Whether you have been lucky enough to visit the Taj Mahal yourself and want a special souvenir of the experience, dream of visiting one day or just appreciate elegant buildings, this LEGO® Architecture Landmarks Collection set (21056) is ideal for you.</p>

<p>Wondrous details<br/>
This inspiring, hands-on challenge to enjoy in your spare time lets you recreate a symbol of eternal love and an architectural wonder of the world in LEGO style. Revel in authentic details such as the crypt with tombs of Mumtaz and Shah Jahan, central chamber with 2 cenotaphs, monumental iwans, main dome, 4 chhatris and 4 slender minarets. A LEGO brick inscribed ‘Taj Mahal’ completes a scale model that is sure to wow people wherever it is displayed.</p>

<p>Delightful gift<br/>
Part of a collection of premium-quality LEGO model kits for adults, this set makes a fantastic treat for yourself. It also makes an inspirational gift for LEGO fans and anyone in your life who is passionate about the Taj Mahal, India, travel or architecture.</p><ul><li>Build and display your own symbol of eternal love with this fabulously detailed LEGO® Architecture Landmarks Collection model (21056) of the Taj Mahal.
</li><li>The crypt with tombs of Mumtaz and Shah Jahan, central chamber with 2 cenotaphs, iwans, main dome, 4 chhatris, 4 minarets and other authentic details are beautifully recreated in LEGO® style.
</li><li>The central chamber can be removed to view the crypt below. The scale model also includes a LEGO® brick inscribed ‘Taj Mahal’ to complete a conversation-starting centerpiece.
</li><li>Whether you’ve been to or dream of visiting India and the Taj Mahal, or you just love travel and architecture, this building set is for you. It also makes a very special gift for creative friends.
</li><li>Measuring 7.5 in. (20 cm) high, 9 in (23 cm) wide and 9 in. (23 cm) deep, this buildable architectural model makes an impressive display piece for your home or office.
</li><li>This collectible, 2,022-piece, construction set is all about the pleasure of immersing yourself in a complex build that leaves you feeling relaxed, refreshed and with a real sense of achievement.
</li><li>Includes step-by-step instructions so even LEGO® beginners can build confidently, plus a booklet telling the Taj Mahal story (English language only. Download other languages at LEGO.com/architecture).
</li><li>This LEGO® Architecture Taj Mahal set is part of a collection of premium-quality building kits designed for adults like you who enjoy hands-on, creative projects.
</li><li>LEGO® components meet rigorous industry standards to ensure that they connect securely and strongly.
</li><li>LEGO® bricks and pieces are dropped, heated, crushed, twisted and analyzed to make sure that they satisfy stringent global safety standards.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/dd07de9f2f20481d15390d10fde53e0e.png', 'slug' => 'taj-mahal', 'created_at' => '2022-05-19 01:06:43', 'updated_at' => '2022-05-19 01:06:43'),
            array('id' => '4', 'name' => '1989 Batwing', 'brand_id' => '2', 'price' => '10000', 'sale_price' => '10000', 'quantity' => '5', 'description' => '<p>This is no kid’s toy. If you’re serious about BATMAN™, comic book super heroes or making cool models, this LEGO® DC BATMAN 1989 Batwing is for you!</p>

<p>Batwing construction project<br/>
Recreate the authentic detail and gothic elegance of BATMAN’s iconic aircraft, the Batwing, with this LEGO brick build-and-display model. The impressive reproduction features realistic details, removable canopy, full interior, poseable flaps and a new special brick that will allow you to mount and display your model on your wall. There’s also a stand, nameplate and 3 minifigures – BATMAN™, THE JOKER™ and a Lawrence the Boombox Goon™ – to create an impressive setting for your model.</p>

<p>LEGO brick model-making kits<br/>
Escape the busy world for a moment and discover the joy of creative construction with adult LEGO building sets. Satisfying to build and stunning to display, adult LEGO kits make great birthday gifts, holiday presents and personal treats for anyone interested in model making or comic culture.</p>
<p>This is no kid’s toy. If you’re serious about BATMAN™, comic book super heroes or making cool models, this LEGO® DC BATMAN 1989 Batwing is for you!</p>

<p>Batwing construction project<br/>
Recreate the authentic detail and gothic elegance of BATMAN’s iconic aircraft, the Batwing, with this LEGO brick build-and-display model. The impressive reproduction features realistic details, removable canopy, full interior, poseable flaps and a new special brick that will allow you to mount and display your model on your wall. There’s also a stand, nameplate and 3 minifigures – BATMAN™, THE JOKER™ and a Lawrence the Boombox Goon™ – to create an impressive setting for your model.</p>

<p>LEGO brick model-making kits<br/>
Escape the busy world for a moment and discover the joy of creative construction with adult LEGO building sets. Satisfying to build and stunning to display, adult LEGO kits make great birthday gifts, holiday presents and personal treats for anyone interested in model making or comic culture.</p><ul><li>Indulge your passion for the Caped Crusader™ with the LEGO® DC BATMAN™ 1989 Batwing. If you’re an adult Batman fan or a model-building enthusiast, this buildable display model of the Batwing is for you!</li><li>The iconic style of the Batwing from the 1989 BATMAN™ movie is enhanced by a sturdy stand, nameplate and 3 minifigures: BATMAN, THE JOKER™ and a Boombox goon.</li><li>This challenging and rewarding building project provides an engrossing and stress-relieving break from the real world – and will look great when displayed on the wall or on its stand in your home or workplace.</li><li>Any superhero or LEGO® fan will love this 2,363-piece construction kit. Whether you buy it for yourself, as a birthday gift or a holiday present, the LEGO Batwing model is sure to deliver hours of enjoyment.</li><li>Measuring over 4” (11cm) high, 20” (52cm) long and 22” (58cm) wide, the LEGO® DC BATMAN™ 1989 Batwing looks stunning on its stand and when attached to the wall.</li><li>No batteries required. This collectible piece of BATMAN™ memorabilia offers a hands-on, build-and-display experience that will catch the eye of every BATMAN, sci-fi or model-making enthusiast.</li><li>Easy-to-follow, high-quality instructions are included to ensure you gain maximum enjoyment from this fascinating construction project.</li><li>Part of a series of authentic LEGO® reproductions designed to deliver a satisfying build-and-display experience. For more in the series, check out the LEGO DC BATMAN™ 1989 Batmobile™.</li><li>No super-powers arerequired to connect and pull apart LEGO® bricks and pieces. They meet the highest industry standard, which ensures they fit together and separate perfectly every time.</li><li>LEGO® bricks and pieces are rigorously tested to ensure your awesome display model meets the highest toy safety standards in GOTHAM CITY™ and the rest of planet Earth.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/15e3c514842f45f7617ed1bfaf379604.png', 'slug' => '1989-batwing', 'created_at' => '2022-05-19 01:08:08', 'updated_at' => '2022-05-19 01:08:08'),
            array('id' => '5', 'name' => 'LEGO® DC Batman™ Batmobile™ Tumbler', 'brand_id' => '2', 'price' => '35000', 'sale_price' => '30000', 'quantity' => '5', 'description' => '<p>LEGO® DC Batman™ Batmobile™ Tumbler (76240) will stretch your construction skills and capture the style of one of the most iconic vehicles in cinema history.</p>

<p>The ultimate, armored crime-fighting machine<br/>
The impressive build-and-display Tumbler from the Dark Knight™ trilogy of Batman movies features an opening roof, which provides access to the driver and passenger seats and control panel. Batman and The Joker™ minifigures are included with a stand. With a sturdy base to display the finished model at its best, your recreation of the Tumbler will provide pleasure long after the hands-on work has been completed.</p>

<p>Adult LEGO kits<br/>
Rediscover the joy of creative construction with adult LEGO building sets. Satisfying to build and stunning to display, adult LEGO kits make great birthday presents, holiday gifts and personal treats for any fan of model making or comic-book culture.</p>
<p>LEGO® DC Batman™ Batmobile™ Tumbler (76240) will stretch your construction skills and capture the style of one of the most iconic vehicles in cinema history.</p>

<p>The ultimate, armored crime-fighting machine<br/>
The impressive build-and-display Tumbler from the Dark Knight™ trilogy of Batman movies features an opening roof, which provides access to the driver and passenger seats and control panel. Batman and The Joker™ minifigures are included with a stand. With a sturdy base to display the finished model at its best, your recreation of the Tumbler will provide pleasure long after the hands-on work has been completed.</p>

<p>Adult LEGO kits<br/>
Rediscover the joy of creative construction with adult LEGO building sets. Satisfying to build and stunning to display, adult LEGO kits make great birthday presents, holiday gifts and personal treats for any fan of model making or comic-book culture.</p><ul><li>Build and display one of cinema’s most iconic vehicles with LEGO® DC Batman™ Batmobile™ Tumbler (76240) – a captivating LEGO brick model created with adults in mind.
</li><li>Includes a buildable Tumbler Batmobile™ with stand, plus Batman™ and The Joker™ minifigures.
</li><li>This armored crime-fighting machine is a collectible piece of Batman™ memorabilia that will provide great satisfaction long after the hands-on, creative construction work is over.
</li><li>If you’re an adult Batman™ fan or model-making enthusiast, this buildable vehicle is the perfect build-and-display project for you.
</li><li>The vehicle measures over 6 in. (16 cm) high, 17 in. (45 cm) long and 9 in. (25 cm) wide and combines easily with other LEGO® DC Batman™ sets.
</li><li>This collectible display model provides stress-relieving escapism as 2,049 LEGO® bricks slowly transform into the spectacular Tumbler.
</li><li>You can embark on this fascinating construction project immediately, thanks to the high-quality printed instructions that are included.
</li><li>The range of LEGO® sets created with adults in mind are designed to deliver a satisfying build-and-display experience that will captivate any model-making enthusiast.
</li><li>LEGO® building kits meet rigorous industry quality standards to ensure they are consistent, compatible and connect and pull apart perfectly every time – it’s been that way since 1958.
</li><li>LEGO® components are dropped, heated, crushed, twisted and analyzed to make sure they meet stringent global safety standards.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/68d774b746e90240c5b88160f2e9b519.png', 'slug' => 'lego-dc-batman-batmobile-tumbler', 'created_at' => '2022-05-19 01:08:09', 'updated_at' => '2022-05-19 01:08:09'),
            array('id' => '6', 'name' => 'Jim Lee Batman™ Collection', 'brand_id' => '2', 'price' => '24000', 'sale_price' => '20000', 'quantity' => '5', 'description' => '<p>Superhero or Super-Villain fans, we have got the set for you. Create 1 of 3 art portraits with this LEGO® Art Jim Lee Batman™ Collection (31205) kit. As you build, you’ll develop other meaningful experiences, such as mindfulness. A zone of joyful zen. Calm focus that enhances creativity as you click each tile into place in this collectible decor piece.</p>

<p>Stand for something<br/>
Build 1 of 3 portraits of iconic DC comics characters: Batman, The Joker™ or Harley Quinn™. Can’t choose? Combine sets to make 1 of 2 ultimate memorabilia pieces. As you create, scan the QR code and listen to the Soundtrack, with nearly 2 hours of content tailor-made to really immerse you in the hobby project. Finish the art with a special signature tile, ready to display on a wall or shelf.</p>

<p>What will you make?<br/>
Welcome to LEGO sets for adults. A space to relax and build detailed craft projects that pay homage to the worlds of entertainment, motorsports, travel, gaming, sports, science, technology and history.</p>

<p>Superhero or Super-Villain fans, we have got the set for you. Create 1 of 3 art portraits with this LEGO® Art Jim Lee Batman™ Collection (31205) kit. As you build, you’ll develop other meaningful experiences, such as mindfulness. A zone of joyful zen. Calm focus that enhances creativity as you click each tile into place in this collectible decor piece.</p>

<p>Stand for something<br/>
Build 1 of 3 portraits of iconic DC comics characters: Batman, The Joker™ or Harley Quinn™. Can’t choose? Combine sets to make 1 of 2 ultimate memorabilia pieces. As you create, scan the QR code and listen to the Soundtrack, with nearly 2 hours of content tailor-made to really immerse you in the hobby project. Finish the art with a special signature tile, ready to display on a wall or shelf.</p>

<p>What will you make?<br/>
Welcome to LEGO sets for adults. A space to relax and build detailed craft projects that pay homage to the worlds of entertainment, motorsports, travel, gaming, sports, science, technology and history.</p>
<ul><li> Pick from 3 designs – Choose justice or the agents of chaos as you build this LEGO® Art Jim Lee Batman™ Collection (31205) wall art set, featuring a portrait kit with 3 build options
</li><li> Made for display – This immersive 4,167-piece LEGO® project includes 9 canvas wall decor plates, a signature tile, 2 hanger elements, a color palette, brick separator and a brick-built frame
</li><li> Designed for DC Universe fans – Showcase the talent of comic book legend Jim Lee by creating 1 of 3 portraits of Batman™, The Joker™ or Harley Quinn™ in LEGO® tiles
</li><li> Find your creative zone – Enter a realm of total relaxation and joyful focus with the Soundtrack, which immerses you in unexpected details as you produce this art project
</li><li> Celebrate your passion – To stretch your creativity further, combine 2 or 3 of the sets to create 1 of 2 Batman™ inspired wall art pieces to display in your home or office
</li><li> Give as a gift – This LEGO® Art set measures over 15.5 in. (40 cm) square and can be displayed on a wall or shelf. It can also be given as a gift for anyone who’s into Super-Villains or Batman™
</li><li> Illustrated guide – The coffee-table-quality instructions guide you through the project, starting with a deep dive into the inspiration behind the LEGO® Art Jim Lee Batman™ Collection before building
</li><li> Building projects for adults – Pay tribute to entertainment icons with LEGO® Art sets for adults. Enter a world of artists and entertainers while you explore your passion for creative arts and crafts
</li><li> High quality – LEGO® building pieces meet exacting quality standards that ensure they are consistent, compatible and work every time: it’s been that way since 1958
</li><li> Safety first – LEGO® pieces are tested to ensure that every LEGO Art building set meets strict safety standards, ensuring this Jim Lee Batman™ Collection wall decor piece is completely robust</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/0a224aef716d0d80220dba6558f8b05a.png', 'slug' => 'jim-lee-batman-collection', 'created_at' => '2022-05-19 01:08:10', 'updated_at' => '2022-05-19 01:08:10'),
            array('id' => '7', 'name' => 'Rocket Launch Center', 'brand_id' => '3', 'price' => '30000', 'sale_price' => '30000', 'quantity' => '5', 'description' => '<p>This LEGO® City Rocket Launch Center (60351) toy playset is packed with NASA-inspired features, including a huge launch tower and a rocket with room for 2 astronauts and a planet rover. There’s also a detailed observation dome and launch control center, plus a service vehicle, drone and 6 minifigures for fun role play. Combine this set with others from the popular LEGO City Space toy range for even more fun.</p>

<p>Digital building instructions for ages 7 and up<br/>
This LEGO toy playset includes a printed building guide and interactive digital building instructions. Available in the free LEGO Building Instructions app for smartphones and tablets, the digital guide comes with awesome zoom and rotate tools that allow kids to visualize each model from all angles as they build.</p>

<p>The creative world of LEGO City<br/>
LEGO City Space toys come with feature-rich models inspired by real NASA machines, vehicles and spacecraft, plus inspiring astronaut characters for imaginative, realistic space play.</p>
<p>This LEGO® City Rocket Launch Center (60351) toy playset is packed with NASA-inspired features, including a huge launch tower and a rocket with room for 2 astronauts and a planet rover. There’s also a detailed observation dome and launch control center, plus a service vehicle, drone and 6 minifigures for fun role play. Combine this set with others from the popular LEGO City Space toy range for even more fun.</p>

<p>Digital building instructions for ages 7 and up<br/>
This LEGO toy playset includes a printed building guide and interactive digital building instructions. Available in the free LEGO Building Instructions app for smartphones and tablets, the digital guide comes with awesome zoom and rotate tools that allow kids to visualize each model from all angles as they build.</p>

<p>The creative world of LEGO City<br/>
LEGO City Space toys come with feature-rich models inspired by real NASA machines, vehicles and spacecraft, plus inspiring astronaut characters for imaginative, realistic space play.</p><ul><li>LEGO® City space-themed playset – The LEGO City Rocket Launch Center (60351) playset comes with an array of NASA-inspired toys for imaginative space play</li><li>What’s in the box? – Everything kids need to build a rocket, launch tower, detailed observatory and launch control center, plus a service vehicle, planet rover, drone and 6 minifigures</li><li>Designed for creative play – Kids can operate the launch tower elevator to deliver the astronauts to the boarding gangway and play out scenarios in the toy space observatory and rocket launch center</li><li>A gift for kids and space fans – This LEGO® space toy can be given as a birthday, holiday or any-other-day surprise for budding astronauts aged 7 and up</li><li>Rocket dimensions – When built, the toy space rocket, including boosters, measures over 16.5 in. (42 cm) high and 4 in. (11 cm) wide</li><li>Accessories add to the fun – This toy playset is packed with LEGO® minifigure accessories, including a planet rover with a pretend light-brick laser that shines a red light (battery included)</li><li>Includes an interactive digital building guide – Kids can zoom, rotate and view models from all angles as they build with the LEGO® Building Instructions app, available for smartphones and tablets</li><li>Building kids’ creative skills – LEGO® City Space toys are inspired by real NASA machines, vehicles and spacecraft for open-ended creative play based on real-life events</li><li>Quality in focus – All LEGO® components meet strict industry standards to ensure they are consistent, compatible and fun to build with: it’s been that way since 1958</li><li>Putting safety first – LEGO® bricks and pieces are dropped, heated, crushed, twisted and analyzed to make sure they meet stringent global standards for safety</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/d52730ed3b2e94f387660716182a8315.png', 'slug' => 'rocket-launch-center', 'created_at' => '2022-05-19 01:10:26', 'updated_at' => '2022-05-19 01:10:26'),
            array('id' => '8', 'name' => 'Cargo Train', 'brand_id' => '3', 'price' => '25000', 'sale_price' => '25000', 'quantity' => '5', 'description' => '<p>Load up the powerful LEGO® City 60198 Cargo Train and deliver the goods on time! This cool LEGO City set features a motorized engine with 10-speed Bluetooth remote control, accessible driver’s cabin, a crane wagon with rotating and extendable boom arm, container wagon with 2 containers, and a log wagon, plus an armored truck with opening doors, and a forklift with opening roll cage and lifting forks. This cool LEGO train set also includes a full circular track with 16 curved rails, 16 straight rails and a railroad switch with lever, plus a control center with ladder and 2 buildable pallets with money bills, gold bar elements, a snow scooter and 6 LEGO minifigures.                                                                                                                                                                                                                                                                                                                                        </p>
<p>Load up the powerful LEGO® City 60198 Cargo Train and deliver the goods on time! This cool LEGO City set features a motorized engine with 10-speed Bluetooth remote control, accessible driver’s cabin, a crane wagon with rotating and extendable boom arm, container wagon with 2 containers, and a log wagon, plus an armored truck with opening doors, and a forklift with opening roll cage and lifting forks. This cool LEGO train set also includes a full circular track with 16 curved rails, 16 straight rails and a railroad switch with lever, plus a control center with ladder and 2 buildable pallets with money bills, gold bar elements, a snow scooter and 6 LEGO minifigures.                                                                                                                                                                                                                                                                                                                                        </p><ul><li> Includes 6 LEGO® minifigures: 4 train workers, a security officer and a crook.
</li><li> Features a motorized engine with 10-speed Bluetooth remote control, pantograph on the opening roof, and driver’s cabin with control panel.
</li><li> Also features a log wagon, crane wagon with rotating and extendable boom arm, and a container wagon with 2 containers with hooks on the roof for loading and space for pallets.
</li><li> Includes a control center with ladder and signal lights, a full circular toy train track with 16 curved rails, 16 straight rails and a railroad switch with lever, a money transport truck with opening doors, and a working forklift with opening roll cage.
</li><li> Accessory elements include a wrench, 12 gold bar elements and 4 money bills, plus 2 buildable pallets, 3 logs and snow scooter.
</li><li> Open the roof to access the engine car filled with cool details.
</li><li> Operate the cargo train with the 10-speed Bluetooth remote control.
</li><li> Lift and load logs onto the log wagon with the crane\'s rotating arm and hook.
</li><li> Push the lever on the railroad switch to drive the train to a different track for loading or unloading.
</li><li> Load pallets into the containers with the forklift before lifting them onto the container wagon with the crane.
</li><li> Set up the tracks in different configurations to load or offload cargo around your city.
</li><li> This product requires batteries (not included). Please refer to the product packaging for type and quantities.
</li><li> The included Bluetooth remote is not compatible with older infrared remote-controlled LEGO® train sets.
</li><li> Cargo Train in total measures over 4” (11cm) high, 32” (82cm) long and 2” (6cm) wide.
</li><li> Engine measures over 4” (11cm) high, 10” (27cm) long and 2” (6cm) wide.
</li><li> Log wagon measures over 1” (5cm) high, 5” (15cm) long and 2” (6cm) wide.
</li><li> Crane wagon measures over 4” (10cm) high, 8” (22cm) long and 1” (5cm) wide.
</li><li> Container wagon measures over 3” (9cm) high, 7” (18cm) long and 1” (5cm) wide.
</li><li> Armored truck measure over 2” (6cm) high, 6” (15cm) long and 2” (6cm) wide.
</li><li> Control center measures over 8” (21cm) high, 3” (8cm) wide and 4” (12cm) deep.
</li><li> Forklift measures over 2” (7cm) high, 2” (5cm) wide and 4” (12cm) deep.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/92c97f03b82c2012fbc39c3a3a2f63d5.png', 'slug' => 'cargo-train', 'created_at' => '2022-05-19 01:10:26', 'updated_at' => '2022-05-19 01:10:26'),
            array('id' => '9', 'name' => 'Pirate Ship', 'brand_id' => '4', 'price' => '27000', 'sale_price' => '27000', 'quantity' => '5', 'description' => '<p>The high seas are calling! Swashbuckling adventures await pirate fans in the LEGO® Creator 3in1 Pirate Ship (31109) toy. This awesome, detailed set features a pirate ship with moving sails, cannons and a cabin with opening roof and sides, 3 minifigures, buildable figures including a shark and a parrot, plus lots of other brick-built details and cool accessories to jump-start play.</p>

<p>Freedom to create and imagine<br/>
At least 3 different build-and-play experiences are possible with this LEGO Creator 3in1 toy set. Kids can build a Pirate Ship, then rebuild it into the Pirates’ Inn or a creepy Skull Island. Or they can let their creativity loose and design something new.</p>

<p>Endless play possibilities await<br/>
LEGO Creator 3in1 sets offer kids different models that are realistic and encourage imaginative play. The models give endless building and play opportunities while helping to spark creativity in children of all ages. The awesome toy sets also make great Christmas gifts or birthday presents for kids.</p>
<p>The high seas are calling! Swashbuckling adventures await pirate fans in the LEGO® Creator 3in1 Pirate Ship (31109) toy. This awesome, detailed set features a pirate ship with moving sails, cannons and a cabin with opening roof and sides, 3 minifigures, buildable figures including a shark and a parrot, plus lots of other brick-built details and cool accessories to jump-start play.</p>

<p>Freedom to create and imagine<br/>
At least 3 different build-and-play experiences are possible with this LEGO Creator 3in1 toy set. Kids can build a Pirate Ship, then rebuild it into the Pirates’ Inn or a creepy Skull Island. Or they can let their creativity loose and design something new.</p>

<p>Endless play possibilities await<br/>
LEGO Creator 3in1 sets offer kids different models that are realistic and encourage imaginative play. The models give endless building and play opportunities while helping to spark creativity in children of all ages. The awesome toy sets also make great Christmas gifts or birthday presents for kids.</p><ul><li>LEGO® Creator 3in1’s Pirate Ship (31109) set encourages kids’ creative play, featuring 3 models in 1: A classic Pirate Ship, rustic Pirates’ Inn and mysterious Skull Island. Building and rebuilding keeps the play going.</li><li>An open bounty of opportunities! Kids can stretch their building and creativity skills with the super-detailed Pirate Ship toy, visit the Pirates\' Inn for a bite, explore Skull Island or create a totally new model.</li><li>This set gives 3 options for building: A LEGO® Creator 3in1 Pirate Ship (31109), Pirates’ Inn or Skull Island, to play with solo or combine with other sets. The set also has 3 minifigures for extra play possibilities.</li><li>Any fan of creative play and building will love this awesome set. The realistic Pirate Ship, Pirates\' Inn and Skull Island models work as a great Christmas, birthday or holiday gift for boys and girls aged 9+.</li><li>The high seas are calling! The pirate ship measures over 14” (37cm) high, 18” (46cm) long and 7” (19cm) wide, meaning thisthrilling toy is full of awesome details and big enough for serious solo and group play fun.</li><li>Powered by a child’s imagination for hours of endless fun! Battery-free toys help boost kids’ independent play and problem-solving skills and give them the joy of coming up with new stories all on their own.</li><li>Open the box and the play begins with building and rebuilding any 1 of the 3 model toys. Clear, easy-to-follow instructions help make assembly a snap for kids, leading to joy in construction and loads of creative fun.</li><li>Give children endless opportunities to develop their building skills as they play with LEGO® Creator 3in1 sets. This awesome pirate ship playset lets kids grow their imagination with lots of building opportunities.</li><li>LEGO® building bricks meet the highest industry standards to ensure they are consistent, compatible and connect and pull apart easily every time – it\'s been that way since 1958.</li><li>LEGO® bricks and pieces are dropped, heated, crushed, twisted and analyzed to make sure every kid’s building set meets the highest global safety and quality standards.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/37cbcac9a7f57d933bdc70cfa402078c.png', 'slug' => 'pirate-ship', 'created_at' => '2022-05-19 01:12:02', 'updated_at' => '2022-05-19 01:12:02'),
            array('id' => '10', 'name' => 'Medieval Castle', 'brand_id' => '4', 'price' => '40000', 'sale_price' => '35000', 'quantity' => '5', 'description' => '<p>Kids will love taking a trip back in time with this brilliantly detailed LEGO® Creator 3in1 Medieval Castle (31120). It’s packed with all they need to create captivating stories – a 2-floored Castle toy with an opening gate, water mill, prison, king’s room, 3 minifigures, dragon toy, 3 chickens and a rat. There are also hinges so the Castle can fold open at the back.</p>

<p>3in1 awesome toys fuel kids’ passions<br/>
Creative kids have the chance to build 3 different models with this LEGO Creator 3in1 set. They can start with the Medieval Castle, rebuild it into a castle tower with a catapult or transform it into a bustling marketplace with a water mill, tower and prison.</p>

<p>Fantastic gifts for kids to grip their imaginations<br/>
LEGO Creator 3in1 buildable toys let kids enjoy imaginative play with 3 different models in every box! The possibilities are endless as each model can be rebuilt into something new. Select from a brilliant 3in1 range including crocodiles, fairgrounds and rockets.</p>
<p>Kids will love taking a trip back in time with this brilliantly detailed LEGO® Creator 3in1 Medieval Castle (31120). It’s packed with all they need to create captivating stories – a 2-floored Castle toy with an opening gate, water mill, prison, king’s room, 3 minifigures, dragon toy, 3 chickens and a rat. There are also hinges so the Castle can fold open at the back.</p>

<p>3in1 awesome toys fuel kids’ passions<br/>
Creative kids have the chance to build 3 different models with this LEGO Creator 3in1 set. They can start with the Medieval Castle, rebuild it into a castle tower with a catapult or transform it into a bustling marketplace with a water mill, tower and prison.</p>

<p>Fantastic gifts for kids to grip their imaginations<br/>
LEGO Creator 3in1 buildable toys let kids enjoy imaginative play with 3 different models in every box! The possibilities are endless as each model can be rebuilt into something new. Select from a brilliant 3in1 range including crocodiles, fairgrounds and rockets.</p><ul><li>The LEGO® Creator 3in1 Medieval Castle (31120) building set will enchant imaginative kids with 3 models in 1 – a Medieval Castle, castle tower and medieval marketplace.</li><li>This medieval toy set also includes 3 minifigures – a blacksmith and 2 medieval guards with impressive weapons to add even more fun to kids’ daring adventures.</li><li>The Castle has 2 floors and hinges so it can fold open at the back for different play options. It also features an opening gate, smithy, water mill, king’s room and a prison.</li><li>The castle tower is accompanied by a working catapult toy, while the medieval marketplace features a water mill, guard tower and prison.</li><li>This 1,426-piece LEGO® Creator 3in1 Castle toy is a rewarding building task for creative kids aged 9 and up and makes a great birthday or holiday gift.</li><li>This Castle toy for kids measures over 10.5 in. (26 cm) high, 12 in. (31 cm) wide and 11 in. (28 cm) deep – a great size for play or to proudly display in a bedroom.</li><li>Look out for other new-for-2021 LEGO® Creator 3in1 sets: Space Shuttle Adventure (31117) and Ferris Wheel (31119).</li><li>The 3 different models can be attached to each other to create an eye-catching mega castle if 3 separate boxes are purchased.</li><li>For more than 6 decades LEGO® building bricks have been made from high-quality materials to ensure they consistently connect and pull apart every time.</li><li>LEGO® building bricks meet stringent global safety standards.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/1bdd41622fce74b844a2c58cd061ef74.png', 'slug' => 'medieval-castle', 'created_at' => '2022-05-19 01:12:02', 'updated_at' => '2022-05-19 01:12:02'),
            array('id' => '11', 'name' => 'Caravan Family Holiday', 'brand_id' => '4', 'price' => '25000', 'sale_price' => '25000', 'quantity' => '5', 'description' => '<p>Creative camping adventures and fun are waiting for outdoor fans in the LEGO® Creator 3in1 Caravan Family Holiday (31108) playset. The set has a retro car and caravan toy and features a kitchen, toilet, removable roof and opening side. Packed with accessories and features, the set also includes 3 minifigures to jump-start play.</p>

<p>Limitless building creativity<br/>
At least 3 different build-and-play experiences are possible with this great LEGO Creator 3in1 toy set. Kids can build a caravan with aretro car model, then rebuild it into a camper van or a detailed lighthouse. Or they can free their creativity, tap into different passions and build something new.</p>

<p>Stand-alone models free imagination<br/>
LEGO Creator 3in1 sets offer kids different models that are realistic and encourage imaginative play. The models give endless building and play opportunities while helping to spark creativity in children of all ages. The awesome toy sets also make great Christmas gifts or birthday presents forkids.</p>
<p>Creative camping adventures and fun are waiting for outdoor fans in the LEGO® Creator 3in1 Caravan Family Holiday (31108) playset. The set has a retro car and caravan toy and features a kitchen, toilet, removable roof and opening side. Packed with accessories and features, the set also includes 3 minifigures to jump-start play.</p>

<p>Limitless building creativity<br/>
At least 3 different build-and-play experiences are possible with this great LEGO Creator 3in1 toy set. Kids can build a caravan with aretro car model, then rebuild it into a camper van or a detailed lighthouse. Or they can free their creativity, tap into different passions and build something new.</p>

<p>Stand-alone models free imagination<br/>
LEGO Creator 3in1 sets offer kids different models that are realistic and encourage imaginative play. The models give endless building and play opportunities while helping to spark creativity in children of all ages. The awesome toy sets also make great Christmas gifts or birthday presents forkids.</p><ul><li>LEGO® Creator 3in1’s Caravan Family Holiday (31108) set encourages kids’ creative play, featuring 3 models in 1: A family caravan with retro car, camper van or lighthouse. Building and rebuilding extends play endlessly!</li><li>Fun possibilities are around every corner! Kids can stretch their creativity and building skills with the detailed caravan and car toy, hop in the camper van for a holiday, visit the lighthouse or build something new.</li><li>This set gives kids 3 options for play: A LEGO® Creator 3in1 Caravan Family Holiday (31108), camper van or lighthouse. The set also has 3 minifigures and 3 different brick-built animals for extra play fun.</li><li>Any fan of creative play and building will love this awesome set. The detailed caravan and retro car, camper van and lighthouse models work as a great Christmas, birthday or holiday gift for boys and girls aged 9+.</li><li>Ready for adventure? The caravan and retro car model measures over 5” (13cm) high, 13” (34cm) long and 4” (12cm) wide, meaningthis exciting action toy is full of awesome details and big enough for serious holiday fun!</li><li>Powered by a child’s imagination for hours of endless fun! Battery-free toys help boost kids’ independent play and problem-solving skills and give them the joy of coming up with new stories all on their own.</li><li>Open the box and the play begins with building and rebuilding any 1 of the 3 model toys. Easy-to-follow instructions help make assembly a snap for kids, leading to pride in construction and loads of creative fun.</li><li>Give children endless possibilities to develop building skills as they play with LEGO® Creator 3in1 sets. This clever outdoor family vacation playset lets kids grow their imaginations with lots of building opportunities.</li><li>LEGO® building bricks meet the highest industry standards to ensure they are consistent, compatible and connect and pull apart easily every time – it\'s been that way since 1958.</li><li>LEGO® bricks and pieces are dropped, heated, crushed, twisted and analyzed to make sure every kid’s building set meets the highest global safety and quality standards.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/f6bf59a85d393107df48d50524d61272.png', 'slug' => 'caravan-family-holiday', 'created_at' => '2022-05-19 01:12:03', 'updated_at' => '2022-05-19 01:12:03'),
            array('id' => '12', 'name' => 'Colosseum', 'brand_id' => '5', 'price' => '50000', 'sale_price' => '45000', 'quantity' => '5', 'description' => '<p>Nowhere on Earth compares to the majesty of the Colosseum of Rome. So, get ready to escape your everyday life as you take on the biggest ever LEGO® build (as at November 2020) yet. This epic 9,036-piece Colosseum model depicts each part of the famous structure in great detail. Authentic detailing shows the northern part of the outer wall’s facade and its iconic arches. The model features 3 stories, adorned with columns of the Doric, Ionic and Corinthian orders while the attic is decorated with Corinthian pilasters.</p>

<p>An awe-inspiring display piece<br/>
The LEGO Colosseum (10276) rests on an oval display base so the model can be seen from every aspect. It’s one of the biggest LEGO models ever but can easily be picked up, allowing you to look through the arches from all angles.</p>

<p>A building project to savor<br/>
The Colosseum is part of a collection of LEGO models for adults who love beautiful architecture and thoughtful design. It also makes a great gift for architecture enthusiasts and LEGO lovers.</p>
<p>Nowhere on Earth compares to the majesty of the Colosseum of Rome. So, get ready to escape your everyday life as you take on the biggest ever LEGO® build (as at November 2020) yet. This epic 9,036-piece Colosseum model depicts each part of the famous structure in great detail. Authentic detailing shows the northern part of the outer wall’s facade and its iconic arches. The model features 3 stories, adorned with columns of the Doric, Ionic and Corinthian orders while the attic is decorated with Corinthian pilasters.</p>

<p>An awe-inspiring display piece<br/>
The LEGO Colosseum (10276) rests on an oval display base so the model can be seen from every aspect. It’s one of the biggest LEGO models ever but can easily be picked up, allowing you to look through the arches from all angles.</p>

<p>A building project to savor<br/>
The Colosseum is part of a collection of LEGO models for adults who love beautiful architecture and thoughtful design. It also makes a great gift for architecture enthusiasts and LEGO lovers.</p><ul><li> Bring to life your own brick-built model of the mighty Colosseum with this engaging and rewarding LEGO® Colosseum (10276) model kit for adults.
</li><li> With an astounding 9,036 pieces, this Colosseum model is the biggest LEGO® set ever (as at November 2020), providing hours of relaxation for adults who love building sets.
</li><li> Anyone with a passion for architecture models will appreciate the amazing detail packed into this Colosseum souvenir. With 3 stories, the model is adorned with columns of the Doric, Ionic and Corinthian orders.
</li><li> If you’re looking for special gifts for architecture fans or history lovers, this building set is a great choice, providing hours of hands-on building experiences with a stunning Colosseum model to display.
</li><li> This Colosseum architecture model measures over 10.5” (27cm) high, 20.5” (52cm) wide and 23.5” (59cm) deep. With 9,036 pieces it’s one of the biggest LEGO® sets in the world, but is easy to lift and turn.
</li><li> The Romans didn’t need batteries and neither do you! This Colosseum model runs on the power of imagination – no batteries required.
</li><li> This model comes with coffee-table-style building instructions with design and history details to inspire you.
</li><li> Part of a series of inspiring LEGO® building sets designed for LEGO building fans, and hobbyists who love elegant design, beautiful architecture and models packed with detail.
</li><li> LEGO® building bricks meet the highest industry standards, which ensures they are consistent, compatible and connect and pull apart easily every time – it’s been that way since 1958.
</li><li> LEGO® bricks and pieces are rigorously tested to ensure that every building set meets the highest safety and quality standards, so you can be sure that this architectural model is designed to last.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/73bef4940b92a615a8cb0c96b2c1af5e.png', 'slug' => 'colosseum', 'created_at' => '2022-05-19 01:13:45', 'updated_at' => '2022-05-19 01:13:45'),
            array('id' => '13', 'name' => 'Real Madrid – Santiago Bernabéu Stadium', 'brand_id' => '5', 'price' => '27000', 'sale_price' => '27000', 'quantity' => '5', 'description' => '<p>A build to capture the heart of any Real Madrid fan. This LEGO® Real Madrid – Santiago Bernabéu Stadium (10299) building kit for adults lets you build an accurate scale model version of one of the most celebrated soccer stadiums of all time. So kick back and take your time discovering all the details packed into this collectible model.</p>

<p>Match-day drama<br/>
Relive experiences of this legendary stadium as you build the ticket office, seating, tunnel, dugout and pitch. Celebrate historic moments with the scoreboards, goals and banners. Enjoy building iconic details like the 4 corner towers, plus the exterior walkway and stairwells. The model splits in half and the roof lifts off, so you can view the interior before placing your model on display.</p>

<p>Welcome to your zone<br/>
This set is part of a collection of LEGO buildable models for adults. The third in the series of LEGO soccer stadiums, it makes a rewarding project or top gift idea for any Real Madrid fan or collector of soccer memorabilia.</p>

<p>A build to capture the heart of any Real Madrid fan. This LEGO® Real Madrid – Santiago Bernabéu Stadium (10299) building kit for adults lets you build an accurate scale model version of one of the most celebrated soccer stadiums of all time. So kick back and take your time discovering all the details packed into this collectible model.</p>

<p>Match-day drama<br/>
Relive experiences of this legendary stadium as you build the ticket office, seating, tunnel, dugout and pitch. Celebrate historic moments with the scoreboards, goals and banners. Enjoy building iconic details like the 4 corner towers, plus the exterior walkway and stairwells. The model splits in half and the roof lifts off, so you can view the interior before placing your model on display.</p>

<p>Welcome to your zone<br/>
This set is part of a collection of LEGO buildable models for adults. The third in the series of LEGO soccer stadiums, it makes a rewarding project or top gift idea for any Real Madrid fan or collector of soccer memorabilia.</p>
<ul><li> A build for adults – Build a tribute to your soccer heroes as you craft all the details of this LEGO® Real Madrid – Santiago Bernabéu Stadium (10299) model building set
</li><li> Modelled on the original stadium – The LEGO® designers have taken care to incorporate all of the iconic details from the real-life Real Madrid soccer stadium into this scale model version
</li><li> Recognizable features – Spot all the details of the Santiago Bernabéu Stadium, including the pitch, goals, tunnel, dugout, scoreboards, banners, seating and stairs
</li><li> Match-day details – Finishing touches include a printed Real Madrid logo and the team bus
</li><li> Comes apart for viewing – The model splits in half and the roof lifts off, allowing you to view the interior
</li><li> Dimensions – This display model measures over 5.5 in. (14 cm) high, 17.5 in. (44 cm) wide and 15 in. (38 cm) deep
</li><li> Illustrated building instructions – Includes building instructions to guide and inspire you. Discover the history of the stadium, plus interesting details about this LEGO® model
</li><li> A project for adults – This LEGO® set is part of a range of building sets designed for adult building fans who love stunning design, intricate details and elegant architecture
</li><li> Quality materials – LEGO® building bricks are manufactured from high-quality materials. They’re consistent, compatible and connect and pull apart easily every time: it’s been that way since 1958
</li><li> Safety ensured – With LEGO® pieces, safety and quality come first. That’s why they’re rigorously tested, so you can be sure that this model is robust</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/b6f7cac9c9b1b8502b293a2284bf4053.png', 'slug' => 'real-madrid-santiago-bernabeu-stadium', 'created_at' => '2022-05-19 01:13:46', 'updated_at' => '2022-05-19 01:13:46'),
            array('id' => '14', 'name' => 'Camp Nou – FC Barcelona', 'brand_id' => '5', 'price' => '10000', 'sale_price' => '10000', 'quantity' => '5', 'description' => '<p>FC Barcelona fans will love showing their passion for one of the world’s most celebrated soccer clubs with this rewarding building project. Build all the details of the mighty Camp Nou Stadium like the Lateral stand with its iconic ‘Més Que Un Club’ motto and the covered Tribuna stand, with press booths, plus the pitch itself. The model splits into 5 sections for access to each area.</p>

<p>Packed with details<br/>
FC Barcelona fans know how to show their loyalty to their club and this stadium model does just the same! Use the LEGO® elements and sticker sheet to add realistic touches to your Camp Nou stadium model – like the Barça signs, Catalan flag and scoreboards. With a players’ tunnel, VIP entrance and team bus, there are plenty of details to spot.</p>

<p>Bring your passions to life<br/>
This set is part of a collection of LEGO buildable models for adults who appreciate elegant design. It offers a rewarding project or top gift for any FC Barcelona fan or collector of soccer memorabilia.</p>
<p>FC Barcelona fans will love showing their passion for one of the world’s most celebrated soccer clubs with this rewarding building project. Build all the details of the mighty Camp Nou Stadium like the Lateral stand with its iconic ‘Més Que Un Club’ motto and the covered Tribuna stand, with press booths, plus the pitch itself. The model splits into 5 sections for access to each area.</p>

<p>Packed with details<br/>
FC Barcelona fans know how to show their loyalty to their club and this stadium model does just the same! Use the LEGO® elements and sticker sheet to add realistic touches to your Camp Nou stadium model – like the Barça signs, Catalan flag and scoreboards. With a players’ tunnel, VIP entrance and team bus, there are plenty of details to spot.</p>

<p>Bring your passions to life<br/>
This set is part of a collection of LEGO buildable models for adults who appreciate elegant design. It offers a rewarding project or top gift for any FC Barcelona fan or collector of soccer memorabilia.</p><ul><li> This spectacular set delivers a rewarding build for adult FC Barcelona fans. Soccer fans will love creating a faithful LEGO® collectible model of FC Barcelona’s iconic Camp Nou stadium.
</li><li> See the faithful interpretation of the pitch, stands and entrance in this LEGO® Camp Nou – FC Barcelona 10284 building set. The model splits into 5 sections for access to each area.
</li><li> Extra details bring the excitement of match day to life. See the press booths, players’ tunnel and team bus, plus banners and flags in the FC Barcelona club colors.
</li><li> This FC Barcelona stadium LEGO® building kit for adults makes for a top gift for anyone who loves soccer memorabilia, FC Barcelona merchandise and collectibles.
</li><li> Measures over 8 in. (20 cm) high, 19 in. (49 cm) wide and 18 in. (46 cm) deep, making an eye-catching display model.
</li><li> Soccer fans will appreciate authentic details like the famous ‘Més Que Un Club’ (More Than A Club) motto in the stands.
</li><li> This set features coffee-table-style building instructions to guide and inspire you. Discover the history of the club and stadium, and read an interview with the LEGO® designer who created the model.
</li><li> This LEGO® Camp Nou – FC Barcelona set is part of a range of buildable model sets designed for adult building fans who love stunning design, intricate details and elegant architecture.
</li><li> LEGO® building bricks are manufactured from high-quality materials. They’re consistent, compatible and connect and pull apart easily every time – it’s been that way since 1958.
</li><li> With LEGO® pieces, safety and quality come first. That’s why they’re rigorously tested so you can be sure that the model is as robust as it is beautiful.</li></ul>', 'status' => '1', 'thumbnail' => 'http://127.0.0.1:8000/upload/b8ca68c85ee0a6aa4bafdaee22869245.png', 'slug' => 'camp-nou-fc-barcelona', 'created_at' => '2022-05-19 01:13:46', 'updated_at' => '2022-05-19 01:38:02')
        );
        if (DB::table('products')->count() === 0) {
            DB::table('products')->insert($products);
        }
    }
}
