### LOGIN
POST http://localhost:8000/api/auth/login
content-type: application/json

{
   "email":"test@gmail.com",
   "password":"12345"
}

### REGISTER
POST http://localhost:8000/api/auth/registry
content-type: application/json

{
   "fullname":"Duy Trung",
   "email":"test@gmail.com",
   "password":"12345"
}

### ME
POST http://localhost:8000/api/auth/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxNzUxMywiZXhwIjoxNjUxMjE3NTczLCJuYmYiOjE2NTEyMTc1MTMsImp0aSI6IjhhT2NkaDQ0SU45VlhRSmoiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.jKT7Ad7-EXzFWJ4k9i0XaU66qX0V5cdawv74G3u6L5E

### LOGOUT
POST http://localhost:8000/api/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxNTYyOCwiZXhwIjoxNjUxMjE1OTI4LCJuYmYiOjE2NTEyMTU2MjgsImp0aSI6IkpQNlRSbElTZW9NSGF5OGMiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.3OBlm7TtmjuKFuyDHZfOCePe6n-BO8LHYL_pc3Qvnpo


### token
POST http://localhost:8000/api/auth/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC90b2tlbiIsImlhdCI6MTY1MTIxNzUxMywiZXhwIjoxNjUxMjE3Njc0LCJuYmYiOjE2NTEyMTc2MTQsImp0aSI6IlJmS25jMmgzTjhtV295eUciLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.noD1XmLpm5pYgtMSpclBfgxKn2TE1ZtxN37OmUszsDc