### LOGIN
POST http://localhost:8000/api/auth/login
content-type: application/json

{
   "email":"test@gmail.com",
   "password":"12345"
}

### REGISTER
POST http://localhost:8000/api/auth/registry
content-type: application/json

{
   "fullname":"Duy Trung",
   "email":"test@gmail.com",
   "password":"12345"
}

### ME
POST http://localhost:8000/api/auth/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxMzkzNCwiZXhwIjoxNjUxMjEzOTk0LCJuYmYiOjE2NTEyMTM5MzQsImp0aSI6ImhnNzhwNktqbXEzenBWbmciLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.hGtp-Jt-NGGFhctvea_3kUyHjdOG5xlmkaTFLbunHAs

### LOGOUT
POST http://localhost:8000/api/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxMTQxOSwiZXhwIjoxNjUxMjE1MDE5LCJuYmYiOjE2NTEyMTE0MTksImp0aSI6IktQUWpHcGxvSVdpUVJnMTgiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.0Nty1YetErCrp2FJg8arGowFXfPlTSDvYGbju-u5D6c


### token
POST http://localhost:8000/api/auth/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxNDY0MSwiZXhwIjoxNjUxMjE0NzAxLCJuYmYiOjE2NTEyMTQ2NDEsImp0aSI6ImZ2SGlyQkZSRGdneWhEalYiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xgY9es0ZE_jikPp-RXGfQ_EOEWZ51G8zTGFu59EYQho