### LOGIN
POST http://localhost:8000/api/auth/login
content-type: application/json

{
   "email":"test@gmail.com",
   "password":"12345"
}

### REGISTER
POST http://localhost:8000/api/auth/registry
content-type: application/json

{
   "fullname":"Duy Trung",
   "email":"test@gmail.com",
   "password":"12345"
}

### ME
POST http://localhost:8000/api/auth/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxMjA5NiwiZXhwIjoxNjUxMjEyMTU2LCJuYmYiOjE2NTEyMTIwOTYsImp0aSI6Ik9YSXdLcW1hN1NEQ28xTTEiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.qh1ENDnbBAvpXivRnI3aBr5tEqEEa97a2GAKmmV9YuQ

### LOGOUT
POST http://localhost:8000/api/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxMTQxOSwiZXhwIjoxNjUxMjE1MDE5LCJuYmYiOjE2NTEyMTE0MTksImp0aSI6IktQUWpHcGxvSVdpUVJnMTgiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.0Nty1YetErCrp2FJg8arGowFXfPlTSDvYGbju-u5D6c


### token
POST http://localhost:8000/api/auth/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY1MTIxMjI5MiwiZXhwIjoxNjUxMjEyMzUyLCJuYmYiOjE2NTEyMTIyOTIsImp0aSI6Ik1aNFN3UlVJRlVTV1p0a0UiLCJzdWIiOjQsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.MDZMYFkXCSH0V145ov9f8k8YUqLnQUxa2AwWQy_gppE